services:
    database:
        image: picasso/database:latest
        networks:
            - picasso_network
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_SSL: ${POSTGRES_SSL}

    server:
        image: picasso/server:latest
        volumes:
          - "./configs/config.yml:/config.yml"
          - "./server/images:/picasso/images"
        networks:
            - picasso_network
        ports:
          - "9000:9000"
        depends_on:
            database:
                condition: service_healthy

networks:
    picasso_network:
        ipam:
            driver: default
            config:
                - subnet: 4.0.1.0/24
                  gateway: 4.0.1.1
