################################################################
# Builds database.
################################################################
FROM SOME_DOCKER_IMAGE as stage1

# Copy in configuration files